[project]
name = "GDPR_Obfuscator"
version = "2024.0.0"
readme = "README.md"
dependencies = ["boto3"]

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages]
find={}

